#!/bin/bash

root() {
    su -c "$*"
}

base_packages=(
    bash-completion
    blueman
    foot
    gnome-themes-extra
    grimshot
    gsimplecal
    mako-notifier
    network-manager-gnome
    pavucontrol
    qt5ct
    qt5-style-plugins
    sway
    swaybg
    swayidle
    swaylock
    tofi
    waybar
    wayland-protocols
    xwayland
)

extra_packages=(
    firefox
    gimp
    git
    gparted
    inkscape
    imv
    liferea
    mousepad
    mpv
    network-manager-openvpn
    openvpn
    pcmanfm
    qbittorrent
    quodlibet
    ssh
    zathura
    xarchiver
)

echo -n "Install extra packages? [y/n] "
read answer

if [ "$answer" != "${answer#[Yy]}" ]; then
    root apt install -y ${base_packages[@]}
    root apt install -y ${extra_packages[@]}
else
    root apt install -y ${base_packages[@]}
fi

echo "Done."