#!/bin/bash

root() {
    su -c "$*"
}

base_packages=(
    bash-completion
    blueman
    foot
    gnome-themes-extra
    grimshot
    gsimplecal
    lm-sensors
    mako-notifier
    network-manager-gnome
    pavucontrol
    qt5ct
    qt5-style-plugins
    sway*<
    thinkfan
    waybar
    wayland*
    wofi
    xwayland
)

extra_packages=(
    atril
    firefox
    gimp
    git
    gparted
    inkscape
    liferea
    mousepad
    network-manager-openvpn
    openvpn
    parole
    qbittorrent
    quodlibet
    ristretto
    ssh
    thunar
    xarchiver
)

echo -n "Install extra packages? [y/n] "
read answer

if [ "$answer" != "${answer#[Yy]}" ]; then
    root apt install -y ${base_packages[@]}
    root apt install -y ${extra_packages[@]}
else
    root apt install -y ${base_packages[@]}
fi

echo "Done."