[main]
pad=10x10
shell=/bin/bash
letter-spacing=0

font=Iosevka Term:size=10
font-bold=Iosevka Term:weight=bold:size=10
font-italic=Iosevka Term:slant=italic:size=10
font-bold-italic=Iosevka Term:weight=bold:slant=italic:size=10

# include=/usr/share/foot/themes/

[cursor]
blink=yes
style=underline

[mouse]
hide-when-typing=yes

[scrollback]
lines=10000
multiplier=3.0
indicator-format=percentage

[key-bindings]
show-urls-launch=Control+Shift+o
# clipboard-copy=Control+c XF86Copy
# clipboard-paste=Control+v XF86Paste

[colors-dark]
alpha=0.7

foreground=e0e0e0
background=111111

regular0=1c1c1c
regular1=cc4444
regular2=529961
regular3=cfa053
regular4=4a7bb0
regular5=9c6ca6
regular6=4fa3a5
regular7=e0e0e0

bright0=555555
bright1=f06262
bright2=70c783
bright3=f0c273
bright4=70a3db
bright5=c794d4
bright6=73c1c4
bright7=ffffff

urls=f0c273
selection-foreground=000000
selection-background=cc4444
